Name: Dhruv Garg

Roll No: 8025320034

Q1 Create a data file by using Python random module with different random generator parameters. The data file must have 20000 X 10000 (rows X columns) in the data file. This data file to be used as database for realization of math and matrix operations in cloud computing lab assignments.

In [ ]:
import numpy as np

#Generating 20000 x 10000 random data
data = np.random.randint(1, 100, size=(20000, 10000))

#Save to file
np.save('data_file.npy', data)

print("Data file created")
print("Shape:", data.shape)

Data file created
Shape: (20000, 10000)


Q2. Write a program in Python to assign subsequent rows to matrix first row elements.

In [ ]:
#Creating a matrix of 6 X 5 using random
matrix = np.random.randint(0, 10, size=(6, 5))
print("Original matrix:\n", matrix)

#Assigning first row to all subsequent rows
matrix[1:] = matrix[0]

print("\nMatrix after assignment:\n", matrix)

Original matrix:
 [[7 2 8 5 7]
 [0 4 0 6 9]
 [3 4 7 9 6]
 [1 4 1 4 1]
 [9 7 7 0 7]
 [7 1 6 7 1]]

Matrix after assignment:
 [[7 2 8 5 7]
 [7 2 8 5 7]
 [7 2 8 5 7]
 [7 2 8 5 7]
 [7 2 8 5 7]
 [7 2 8 5 7]]


Q3. Write a program in Python to group similar elements into matrix.

In [ ]:
#Input list
data = [2,3,1,4,2,5,2,1,3,6,5,2,7,4,5]

#To store unique values in order
unique_values = []

#To store grouped rows
matrix = []

# Loop through each number in the list
for num in data:
    #If number already exists, add it to that group
    if num in unique_values:
        index = unique_values.index(num)
        matrix[index].append(num)
    #If number is new, create a new group
    else:
        unique_values.append(num)
        matrix.append([num])

#Displaying result
print("Grouped Matrix:")
for row in matrix:
    print(row)

Grouped Matrix:
[2, 2, 2, 2]
[3, 3]
[1, 1]
[4, 4]
[5, 5, 5]
[6]
[7]


Q4. Write a program in Python to add and subtract matrices in python.

In [ ]:
#Adding and Subtracting two matrices
A = np.random.randint(1, 10, size=(3, 3))
B = np.random.randint(1, 10, size=(3, 3))

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

#Add
print("\nA + B:\n", np.add(A, B))

#Subtract
print("\nA - B:\n", np.subtract(A, B))

Matrix A:
 [[3 6 4]
 [6 3 1]
 [4 1 5]]

Matrix B:
 [[6 3 1]
 [7 4 1]
 [5 9 4]]

A + B:
 [[ 9  9  5]
 [13  7  2]
 [ 9 10  9]]

A - B:
 [[-3  3  3]
 [-1 -1  0]
 [-1 -8  1]]


Q5. Write a program in Python to create an n x n square matrix, where all the sub-matrix has the sum of opposite corner elements as even.

In [ ]:
def create_even_corner_matrix(n):
    matrix = np.zeros((n, n), dtype=int)
    for i in range(n):
        for j in range(n):
            matrix[i][j] = 2 * (i + j)
    return matrix

n = 4
matrix = create_even_corner_matrix(n)
print("Matrix:\n", matrix)

# Verify opposite corners of full matrix
print("\nTop-left corner:", matrix[0][0])
print("Bottom-right corner:", matrix[n-1][n-1])
print("Sum:", matrix[0][0] + matrix[n-1][n-1], "-> Even?", (matrix[0][0] + matrix[n-1][n-1]) % 2 == 0)

Matrix:
 [[ 0  2  4  6]
 [ 2  4  6  8]
 [ 4  6  8 10]
 [ 6  8 10 12]]

Top-left corner: 0
Bottom-right corner: 12
Sum: 12 -> Even? True


Q6 Write a program in Python to perform row-wise element addition in tuple matrix

In [ ]:
#Creating a matrix of tuples
tuple_matrix = [
    (10, 20, 30, 40),
    (15, 25, 35, 45),
    (5,  15, 25, 35)
]

print("Original tuple matrix:")
for row in tuple_matrix:
    print(row)

#Row-wise element addition
row_sums = [sum(row) for row in tuple_matrix]

print("\nRow-wise sums:", row_sums)

Original tuple matrix:
(10, 20, 30, 40)
(15, 25, 35, 45)
(5, 15, 25, 35)

Row-wise sums: [100, 120, 80]
